### ISSUE TITLE
Formal Verification Scope and Specification

### ISSUE THREAD

**Issue by eozturk1** [microsoft/Nimble#6]
Very nice work and congrats on getting accepted to OSDI'23!

The [paper](https://www.usenix.org/system/files/osdi23-angel.pdf) mentions that Nimble's core protocol was formally verified using Dafny. I was wondering what the scope of the "core protocol" is. Does it include all protocols described in the paper including reconfiguration?

Also, will the formal verification source code be open-sourced as well? I couldn't see it in this repo but I'd appreciate if you could share a pointer if it is open-sourced somewhere else.

Thank you!

**Comment by sga001** [comment]
No, the formal verification effort does not include reconfiguration. It comprises the protocol in Section 5.1 in the paper.

We have not yet open-sourced the formal verification code. It seems multiple people have asked us for this, so we will look into it.

**Comment by eozturk1** [comment]
Thanks for the response @sga001!
